/** Estructuras de selección
 * 
 */
public class EstructurasSeleccion {
    public static void main(String[] args) {
        
        boolean condicion = false;
        boolean condicion1 = false;
        boolean condicion2 = false;
        boolean condicion3 = false;

        // ----------------------------------------------------------
        if(condicion)
            // una única linea
        // ----------------------------------------------------------
        if(condicion){
            // ...
            // ...
        }
        // ----------------------------------------------------------
        if(condicion)
            System.out.println("Dentro de else"); // una única linea
        else
            System.out.println("Dentro de else"); // una única linea
        // ----------------------------------------------------------
        if(condicion){
            // ...
            // ...
        }
        else{
            // ...
            // ...
        }
        // ----------------------------------------------------------
        if(condicion1){
            // ...
            // ...
        }
        else{
            if(condicion2){
                // ...
                // ...
            }
            else{
                if(condicion3){
                    // ...
                    // ...
                }
                else{
                    // ...
                    // ...
                }
            }
            // ...
            // ...
        }
        // ----------------------------------------------------------
        if(condicion1){
            // ...
            // ...
        }
        else if(condicion2){
            // ...
            // ...
        }
        else if(condicion3){
            // ...
            // ...
        }
        else{
            // ...
            // ...
        }

    }
}
